name: app-galaxy-map

services:
  app:
    build: ./src
    environment:
      "ConnectionStrings:GalaxyMapContext": Host=app-galaxy-map-db-1;Port=5432;Userid=app_galaxy_map_user;Password=password;Database=galaxy
    ports:
      - "1798:3000"
    volumes:
      - ./src:/app/src
  db:
    image: "postgres:17.0-bookworm"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./db:/data/db
